# Generated by Django 3.2.9 on 2021-11-28 16:51

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('idade', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Idade')),
                ('registroAcademico', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Registro Academico')),
                ('email', models.TextField(max_length=200, verbose_name='email')),
                ('imagem', stdimage.models.StdImageField(upload_to='Aluno', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAluno.materias', verbose_name='Materias')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ('nome',),
            },
        ),
    ]
