# Generated by Django 3.2.9 on 2021-11-28 17:30

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('registroAcademico', models.IntegerField(verbose_name='Registro Academico')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('imagem', stdimage.models.StdImageField(upload_to='Aluno', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug')),
                ('notas', models.IntegerField(verbose_name='Notas')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAluno.materias', verbose_name='Materias')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ('nome',),
            },
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
