# Generated by Django 3.2.9 on 2021-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAluno', '0002_auto_20211128_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materias',
            options={'ordering': ('nome',), 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
        migrations.AlterField(
            model_name='alunos',
            name='notas',
            field=models.IntegerField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='registroAcademico',
            field=models.CharField(max_length=10, verbose_name='Registro Academico'),
        ),
    ]
