# Generated by Django 3.2.9 on 2021-11-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAluno', '0003_auto_20211128_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='registroAcademico',
            field=models.CharField(max_length=8, verbose_name='Registro Academico'),
        ),
    ]
